Added bcmath support for Appengine
Appengine requires bccomp to function.

_PHPEnvironmentError: The PHP runtime requires the "bccomp" function, which is not defined.                                                                                                                                            
If you built PHP using "configure" then please rebuild with:                                                                                                                                                                           
 ./configure  --enable-bcmath